app1/urls.py
from django.urls import path
from app1.views import *

app_name='nothing'

urlpatterns=[
    path('harly/',harly,name='harly')
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='nothing1'

urlpatterns=[
    path('harly1/',harly1,name='harly1')
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def harly(request):
    return render(request,'harly.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def harly1(request):
    return render(request,'harly1.html')

templates/harly.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1 style="color: aqua;">BIKE COLLECTION</h1>
        <h2>HARLY DAVIDSON</h2>
        <h2>DUCATI</h2>
        <a href="{% url 'nothing1:harly1' %}">details</a>
    </center>
    
</body>
</html>

templates/harly1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   
        <h2>HARLY DAVIDSON</h2>
        <img src="https://tse3.mm.bing.net/th?id=OIP.J7A4yEmYo-nt4EC770aiZQHaE7&pid=Api&P=0" alt="">
        <p>The pursuit of adventure begins with a ride on a Harley-Davidson® motorcycle. Make any weekend epic. Turn your commute into a daily thrill-seeker.A Harley-Davidson® blows things wide open. Pure freedom. As big and real as it gets.</p>
        <a href="{% url 'nothing:harly' %}">details</a>
        <h2>DUCATI</h2>
        <img src="https://tse4.mm.bing.net/th?id=OIP.eW9MqqgM8jkpuN-_EIS1OQHaF4&pid=Api&P=0" alt="">
</body>
</html>